spring:
  data:
    mongodb:
      uri: mongodb+srv://thanhnghiat42_db_user:yqpvwPOczWuExr0J@coursedb.oind0z4.mongodb.net/?appName=courseDb
      database: courseDb
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: seanpaul1402@gmail.com
    password: "bsuu joea zjdl koqc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

# API key for mailbox validation
mailboxlayer:
  api:
    key: 19dacce41e42ff30bc496ec3164e1cb0

# JWT secret key
jwt:
  secret: shapio-super-secret-key-abcxyz1234567890

# App file upload config
app:
  upload-dir: uploads/

# ============================================
# VNPAY Payment Configuration
# ============================================
vnpay:
  # Merchant Info (Merchant riêng của bạn)
  tmn-code: 60SBCZFK
  hash-secret: O59YV1KLUB235EX45L5CAFDK1Z1MZUXN

  # VNPAY Gateway URLs
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

  # Callback URLs - DÙNG NGROK PUBLIC URL
  return-url: https://marilyn-unsubordinated-avianna.ngrok-free.dev/api/payment/vnpay/return
  ipn-url: https://marilyn-unsubordinated-avianna.ngrok-free.dev/api/payment/vnpay/ipn

  # Payment Settings
  version: 2.1.0
  command: pay
  order-type: other
  currency-code: VND
  locale: vn
