spring:
  data:
    mongodb:
      uri: mongodb+srv://thanhnghiat42_db_user:yqpvwPOczWuExr0J@coursedb.oind0z4.mongodb.net/?appName=courseDb
      database: courseDb

    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: seanpaul1402@gmail.com
    password: "bsuu joea zjdl koqc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# API key for mailbox validation
mailboxlayer:
  api:
    key: 19dacce41e42ff30bc496ec3164e1cb0

# JWT secret key
jwt:
  secret: shapio-super-secret-key-abcxyz1234567890

# App file upload config
app:
  upload-dir: uploads/

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
